version: '4'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
volumes:
  redis_volume_data:

